export const peminjamanRuanganData = [
  {
    id: 1,
    noSurat: "I/SPH/062/FSI-FMIPA/2025",
    organisasi: "FSI Ulul Albab",
    tempatKegiatan: "Ruang Kuliah I.2.4",
    tanggalPinjam: "22-06-2025",
    tanggalKembali: "22-06-2025",
    status: "Diterima",
    // Detail fields
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "10-06-2025",
    namaKegiatan: "Kajian Rutin Mingguan",
    jamMulai: "13:00 WITA",
    jamBerakhir: "16:00 WITA",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Fauzan Abdillah", nim: "2211016310021" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", nim: "2111016210009" },
    keterangan: "Kegiatan kajian rutin mingguan FSI Ulul Albab yang dihadiri oleh seluruh anggota aktif. Kegiatan ini bertujuan untuk meningkatkan pemahaman keagamaan dan mempererat tali silaturahmi antar anggota.",
  },
  {
    id: 2,
    noSurat: "I/SPH/061/HIMAFI-FMIPA/2025",
    organisasi: "HIMAFI",
    tempatKegiatan: "Ruang Kuliah I.2.4",
    tanggalPinjam: "21-06-2025",
    tanggalKembali: "21-06-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "25-02-2025",
    namaKegiatan: "Workshop Fisika Modern",
    jamMulai: "08:00 WITA",
    jamBerakhir: "16:00 WITA",
    penanggungJawab: { nama: "Ahmad Suryadi", telp: "081234567890" },
    ketuaPelaksana: { nama: "Rizki Andriansyah", nim: "2011014220015" },
    ketuaOrganisasi: { nama: "Siti Nurhaliza", nim: "2011014220023" },
    keterangan: "Kegiatan workshop ini merupakan bagian dari program kerja HIMAFI untuk meningkatkan pemahaman mahasiswa tentang fisika modern. Diharapkan dapat dihadiri oleh minimal 50 peserta dari berbagai angkatan.",
  },
  {
    id: 3,
    noSurat: "-",
    organisasi: "BEM FMIPA",
    tempatKegiatan: "Ruang Kuliah I.1.2",
    tanggalPinjam: "15-06-2025",
    tanggalKembali: "15-06-2025",
    status: "Ditolak",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "01-06-2025",
    namaKegiatan: "Rapat Koordinasi BEM",
    jamMulai: "09:00 WITA",
    jamBerakhir: "12:00 WITA",
    penanggungJawab: { nama: "Dimas Prasetyo", telp: "082345678901" },
    ketuaPelaksana: { nama: "Anisa Rahmawati", nim: "2111016220034" },
    ketuaOrganisasi: { nama: "Bagas Nugroho", nim: "2011016210017" },
    keterangan: "Rapat koordinasi BEM FMIPA untuk membahas program kerja semester genap. Ditolak karena jadwal ruangan sudah terisi oleh kegiatan lain pada tanggal yang sama.",
  },
  {
    id: 4,
    noSurat: "I/SPH/060/FSI-FMIPA/2025",
    organisasi: "FSI Ulul Albab",
    tempatKegiatan: "Ruang Kuliah I.2.3",
    tanggalPinjam: "15-06-2025",
    tanggalKembali: "15-06-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "05-06-2025",
    namaKegiatan: "Seminar Keislaman",
    jamMulai: "08:30 WITA",
    jamBerakhir: "12:00 WITA",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Laila Nurfadillah", nim: "2211016310055" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", nim: "2111016210009" },
    keterangan: "Seminar keislaman dalam rangka memperingati Hari Kebangkitan Nasional. Peserta diperkirakan sebanyak 80 mahasiswa dari berbagai program studi di FMIPA.",
  },
  {
    id: 5,
    noSurat: "I/SPH/059/BDS-FMIPA/2025",
    organisasi: "Birodata Statistika",
    tempatKegiatan: "Ruang Kuliah I.2.6",
    tanggalPinjam: "10-06-2025",
    tanggalKembali: "10-06-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "28-05-2025",
    namaKegiatan: "Pelatihan SPSS dan R",
    jamMulai: "08:00 WITA",
    jamBerakhir: "17:00 WITA",
    penanggungJawab: { nama: "Wahid Nugroho", telp: "083456789012" },
    ketuaPelaksana: { nama: "Putri Statistika", nim: "2311017110042" },
    ketuaOrganisasi: { nama: "Eko Prasetyo", nim: "2111017110003" },
    keterangan: "Pelatihan analisis data menggunakan software SPSS dan R untuk mahasiswa statistika angkatan 2022 dan 2023. Pelatihan ini merupakan program wajib bagi mahasiswa sebelum melaksanakan PKL.",
  },
  {
    id: 6,
    noSurat: "-",
    organisasi: "FSI Ulul Albab",
    tempatKegiatan: "Ruang Kuliah I.2.3",
    tanggalPinjam: "01-06-2025",
    tanggalKembali: "01-06-2025",
    status: "Revisi",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "20-05-2025",
    namaKegiatan: "Tarbiyah Bulanan",
    jamMulai: "13:00 WITA",
    jamBerakhir: "15:30 WITA",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Nadia Mardhatillah", nim: "2311016310068" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", nim: "2111016210009" },
    keterangan: "Kegiatan tarbiyah bulanan FSI Ulul Albab. Surat perlu direvisi karena kolom tanda tangan pembimbing belum dilengkapi dan cap organisasi belum terpasang.",
  },
  {
    id: 7,
    noSurat: "-",
    organisasi: "BEM FMIPA",
    tempatKegiatan: "Ruang Kuliah I.1.1",
    tanggalPinjam: "13-05-2025",
    tanggalKembali: "13-05-2025",
    status: "Ditolak",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "01-05-2025",
    namaKegiatan: "Open Recruitment BEM",
    jamMulai: "10:00 WITA",
    jamBerakhir: "13:00 WITA",
    penanggungJawab: { nama: "Dimas Prasetyo", telp: "082345678901" },
    ketuaPelaksana: { nama: "Rizal Hamdani", nim: "2211016210047" },
    ketuaOrganisasi: { nama: "Bagas Nugroho", nim: "2011016210017" },
    keterangan: "Open recruitment anggota baru BEM FMIPA periode 2025/2026. Ditolak karena pengajuan tidak memenuhi batas waktu minimal 7 hari sebelum pelaksanaan.",
  },
  {
    id: 8,
    noSurat: "I/SPH/058/UPTKM/2025",
    organisasi: "UPTKM FMIPA ULM",
    tempatKegiatan: "Ruang Kuliah II.1.2",
    tanggalPinjam: "26-04-2025",
    tanggalKembali: "26-04-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "14-04-2025",
    namaKegiatan: "Pelatihan Kewirausahaan Mahasiswa",
    jamMulai: "08:00 WITA",
    jamBerakhir: "15:00 WITA",
    penanggungJawab: { nama: "Suharto Wibowo", telp: "084567890123" },
    ketuaPelaksana: { nama: "Mira Aulia", nim: "2211015320028" },
    ketuaOrganisasi: { nama: "Fajar Ramadhan", nim: "2111016210031" },
    keterangan: "Pelatihan kewirausahaan untuk mahasiswa FMIPA sebagai bagian dari program UPTKM. Kegiatan ini menghadirkan pemateri dari alumni sukses dan praktisi bisnis dari Kalimantan Selatan.",
  },
  {
    id: 9,
    noSurat: "I/SPH/057/MSC-FMIPA/2025",
    organisasi: "MSC",
    tempatKegiatan: "Ruang Kuliah I.2.4",
    tanggalPinjam: "13-04-2025",
    tanggalKembali: "13-04-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "01-04-2025",
    namaKegiatan: "Math Study Club Sesi 3",
    jamMulai: "15:00 WITA",
    jamBerakhir: "17:30 WITA",
    penanggungJawab: { nama: "Arif Hidayat", telp: "085678901234" },
    ketuaPelaksana: { nama: "Sari Indah", nim: "2311011210044" },
    ketuaOrganisasi: { nama: "Budi Santoso", nim: "2111011110012" },
    keterangan: "Sesi diskusi dan belajar bersama mata kuliah Aljabar Linear dan Kalkulus Multivariabel. Terbuka untuk seluruh mahasiswa matematika yang ingin meningkatkan pemahaman materi.",
  },
  {
    id: 10,
    noSurat: "I/SPH/056/SGO-FMIPA/2025",
    organisasi: "SGO",
    tempatKegiatan: "Ruang Kuliah II.1.2",
    tanggalPinjam: "08-03-2025",
    tanggalKembali: "08-03-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "24-02-2025",
    namaKegiatan: "Seminar Geografi Lingkungan",
    jamMulai: "08:00 WITA",
    jamBerakhir: "13:00 WITA",
    penanggungJawab: { nama: "Yusuf Maulana", telp: "086789012345" },
    ketuaPelaksana: { nama: "Dewi Kartika", nim: "2211013320016" },
    ketuaOrganisasi: { nama: "Hamdan Noor", nim: "2111013210005" },
    keterangan: "Seminar bertema lingkungan dan perubahan iklim yang menghadirkan narasumber dari BRIN dan Dinas Lingkungan Hidup Provinsi Kalimantan Selatan.",
  },
  {
    id: 11,
    noSurat: "I/SPH/055/HMM-FMIPA/2025",
    organisasi: "HMM FMIPA",
    tempatKegiatan: "Ruang Kuliah I.1.3",
    tanggalPinjam: "20-02-2025",
    tanggalKembali: "20-02-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "07-02-2025",
    namaKegiatan: "Rapat Pleno HMM",
    jamMulai: "09:00 WITA",
    jamBerakhir: "12:00 WITA",
    penanggungJawab: { nama: "Taufik Hidayat", telp: "087890123456" },
    ketuaPelaksana: { nama: "Arifin Maulana", nim: "2211011210033" },
    ketuaOrganisasi: { nama: "Lilis Suryani", nim: "2111011210019" },
    keterangan: "Rapat pleno HMM FMIPA untuk evaluasi program kerja semester ganjil dan penyusunan program semester genap tahun akademik 2024/2025.",
  },
  {
    id: 12,
    noSurat: "-",
    organisasi: "HIMATIKA",
    tempatKegiatan: "Ruang Kuliah I.2.1",
    tanggalPinjam: "14-02-2025",
    tanggalKembali: "14-02-2025",
    status: "Revisi",
    jenisSurat: "Surat Peminjaman Ruangan",
    tanggalPengajuan: "03-02-2025",
    namaKegiatan: "Olimpiade Matematika Internal",
    jamMulai: "08:00 WITA",
    jamBerakhir: "15:00 WITA",
    penanggungJawab: { nama: "Nurfitri Amalia", telp: "088901234567" },
    ketuaPelaksana: { nama: "Dani Pratama", nim: "2311011110027" },
    ketuaOrganisasi: { nama: "Rina Safitri", nim: "2111011110038" },
    keterangan: "Olimpiade matematika internal HIMATIKA yang diikuti oleh mahasiswa matematika seluruh angkatan. Surat perlu direvisi karena tidak mencantumkan estimasi jumlah peserta dan rundown acara.",
  },
];

// Ganti peminjamanAlatBahanData yang lama dengan ini di src/test/data.js

export const peminjamanAlatBahanData = [
  {
    id: 1,
    noSurat: "I/SPH/024/HIMAFI-FMIPA/2025",
    kegiatan: "HIMAFI Mengabdi",
    tanggalPengajuan: "01-07-2025",
    tanggalPinjam: "08-07-2025",
    tanggalKembali: "10-07-2025",
    status: "Diterima",
    // Detail fields
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "HIMAFI",
    penanggungJawab: { nama: "Ahmad Suryadi", telp: "081234567890" },
    ketuaPelaksana: { nama: "Rizki Andriansyah", nim: "2011014220015" },
    ketuaOrganisasi: { nama: "Siti Nurhaliza", telp: "2011014220023" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Sound System - 2" },
      { item: "Item 3", nama: "Meja Lipat - 10" },
    ],
    keterangan: "HIMAFI Mengabdi adalah kegiatan pengabdian masyarakat yang dilakukan oleh HIMAFI FMIPA ULM di daerah sekitar kampus. Kegiatan ini membutuhkan beberapa peralatan untuk mendukung pelaksanaan acara di lapangan.",
  },
  {
    id: 2,
    noSurat: "I/SPH/023/HIMASTA-FMIPA/2025",
    kegiatan: '(BoS) HIMASTA "INFINITE"',
    tanggalPengajuan: "28-05-2025",
    tanggalPinjam: "31-05-2025",
    tanggalKembali: "01-06-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "HIMASTA",
    penanggungJawab: { nama: "Ahmad Suryadi", telp: "081234567890" },
    ketuaPelaksana: { nama: "Rizki Andriansyah", nim: "2011014220015" },
    ketuaOrganisasi: { nama: "Siti Nurhaliza", telp: "2011014220023" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Sound System - 3" },
    ],
    keterangan: 'BoS HIMASTA Infinite adalah kegiatan rapat dan koordinasi internal HIMASTA untuk membahas program kerja serta evaluasi organisasi.',
  },
  {
    id: 3,
    noSurat: "-",
    kegiatan: "BEM Relationship",
    tanggalPengajuan: "25-05-2025",
    tanggalPinjam: "31-05-2025",
    tanggalKembali: "31-05-2025",
    status: "Revisi",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "BEM FMIPA",
    penanggungJawab: { nama: "Dimas Prasetyo", telp: "082345678901" },
    ketuaPelaksana: { nama: "Anisa Rahmawati", nim: "2111016220034" },
    ketuaOrganisasi: { nama: "Bagas Nugroho", telp: "2011016210017" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Mikrofon - 2" },
      { item: "Item 3", nama: "Kursi Lipat - 50" },
    ],
    keterangan: "Kegiatan BEM Relationship bertujuan mempererat hubungan antar organisasi mahasiswa FMIPA. Surat perlu direvisi karena belum mencantumkan tanda tangan pembimbing.",
  },
  {
    id: 4,
    noSurat: "I/SPH/022/SGO-FMIPA/2025",
    kegiatan: "Pentas Anggota Muda SGO",
    tanggalPengajuan: "23-05-2025",
    tanggalPinjam: "23-05-2025",
    tanggalKembali: "27-05-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "SGO",
    penanggungJawab: { nama: "Yusuf Maulana", telp: "086789012345" },
    ketuaPelaksana: { nama: "Dewi Kartika", nim: "2211013320016" },
    ketuaOrganisasi: { nama: "Hamdan Noor", telp: "2111013210005" },
    daftarAlat: [
      { item: "Item 1", nama: "Sound System - 1" },
      { item: "Item 2", nama: "Lighting Set - 1" },
      { item: "Item 3", nama: "Kabel Extension - 5" },
      { item: "Item 4", nama: "Podium - 1" },
    ],
    keterangan: "Pentas Anggota Muda SGO merupakan ajang penampilan perdana bagi anggota baru SGO yang telah menyelesaikan masa orientasi. Kegiatan ini dihadiri oleh seluruh anggota aktif SGO.",
  },
  {
    id: 5,
    noSurat: "I/SPH/021/FSI-FMIPA/2024",
    kegiatan: "Upgrading Dakwah",
    tanggalPengajuan: "20-05-2025",
    tanggalPinjam: "24-05-2025",
    tanggalKembali: "26-05-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "FSI Ulul Albab",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Laila Nurfadillah", nim: "2211016310055" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", telp: "2111016210009" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 2" },
      { item: "Item 2", nama: "Sound System - 1" },
      { item: "Item 3", nama: "Whiteboard - 2" },
    ],
    keterangan: "Upgrading Dakwah FSI Ulul Albab merupakan kegiatan peningkatan kapasitas kader dalam bidang dakwah kampus. Peserta diperkirakan sebanyak 40 orang dari berbagai angkatan.",
  },
  {
    id: 6,
    noSurat: "-",
    kegiatan: "Kelas Mentor 2",
    tanggalPengajuan: "06-05-2025",
    tanggalPinjam: "18-05-2025",
    tanggalKembali: "19-05-2025",
    status: "Ditolak",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "FSI Ulul Albab",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Nadia Mardhatillah", nim: "2311016310068" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", telp: "2111016210009" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Layar Proyektor - 1" },
    ],
    keterangan: "Ditolak karena alat yang diminta sedang dalam jadwal perbaikan dan tidak tersedia pada tanggal yang dimohon.",
  },
  {
    id: 7,
    noSurat: "-",
    kegiatan: "Pembekalan Legislatif",
    tanggalPengajuan: "06-05-2025",
    tanggalPinjam: "09-05-2025",
    tanggalKembali: "12-05-2025",
    status: "Ditolak",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "DPM FMIPA",
    penanggungJawab: { nama: "Irfan Hakim", telp: "089012345678" },
    ketuaPelaksana: { nama: "Rizal Fahmi", nim: "2211016110021" },
    ketuaOrganisasi: { nama: "Wulan Sari", telp: "2111016110008" },
    daftarAlat: [
      { item: "Item 1", nama: "Sound System - 1" },
      { item: "Item 2", nama: "Mikrofon Wireless - 3" },
      { item: "Item 3", nama: "Meja Lipat - 20" },
    ],
    keterangan: "Ditolak karena pengajuan melebihi kapasitas peminjaman alat yang diperbolehkan dalam satu waktu bersamaan dengan peminjam lain.",
  },
  {
    id: 8,
    noSurat: "I/SPH/020/FSI-FMIPA/2025",
    kegiatan: "Kelas Mentor 1",
    tanggalPengajuan: "29-04-2025",
    tanggalPinjam: "11-05-2025",
    tanggalKembali: "14-05-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "FSI Ulul Albab",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Fauzan Abdillah", nim: "2211016310021" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", telp: "2111016210009" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Layar Proyektor - 1" },
      { item: "Item 3", nama: "Sound System - 1" },
    ],
    keterangan: "Kelas Mentor 1 merupakan program mentoring intensif bagi anggota baru FSI Ulul Albab angkatan 2024. Kegiatan berlangsung selama 3 hari dengan materi keislaman dan kepemimpinan.",
  },
  {
    id: 9,
    noSurat: "I/SPH/019/FSI-FMIPA/2025",
    kegiatan: "MUTQIN 1",
    tanggalPengajuan: "25-04-2025",
    tanggalPinjam: "11-05-2025",
    tanggalKembali: "14-05-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "FSI Ulul Albab",
    penanggungJawab: { nama: "Haris Maulana", telp: "081234000001" },
    ketuaPelaksana: { nama: "Salman Al Farisi", nim: "2311016310044" },
    ketuaOrganisasi: { nama: "Rafi Noorhakim", telp: "2111016210009" },
    daftarAlat: [
      { item: "Item 1", nama: "Tenda - 3" },
      { item: "Item 2", nama: "Sound System - 1" },
      { item: "Item 3", nama: "Proyektor - 1" },
      { item: "Item 4", nama: "Generator - 1" },
    ],
    keterangan: "MUTQIN 1 adalah kegiatan outdoor training dan tarbiyah alam terbuka untuk kader FSI Ulul Albab. Kegiatan dilaksanakan di area kampus dan membutuhkan berbagai peralatan lapangan.",
  },
  {
    id: 10,
    noSurat: "I/SPH/018/DPM-FMIPA/2025",
    kegiatan: "DPM Berkunjung",
    tanggalPengajuan: "23-04-2025",
    tanggalPinjam: "25-04-2025",
    tanggalKembali: "28-04-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "DPM FMIPA",
    penanggungJawab: { nama: "Irfan Hakim", telp: "089012345678" },
    ketuaPelaksana: { nama: "Rizal Fahmi", nim: "2211016110021" },
    ketuaOrganisasi: { nama: "Wulan Sari", telp: "2111016110008" },
    daftarAlat: [
      { item: "Item 1", nama: "Kamera - 1" },
      { item: "Item 2", nama: "Tripod - 1" },
    ],
    keterangan: "DPM Berkunjung adalah agenda kunjungan kerja DPM FMIPA ke beberapa instansi terkait untuk belajar tata kelola organisasi. Kamera diperlukan untuk dokumentasi kegiatan.",
  },
  {
    id: 11,
    noSurat: "I/SPH/017/BEM-FMIPA/2025",
    kegiatan: "Seminar Nasional MIPA",
    tanggalPengajuan: "10-04-2025",
    tanggalPinjam: "15-04-2025",
    tanggalKembali: "16-04-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "BEM FMIPA",
    penanggungJawab: { nama: "Dimas Prasetyo", telp: "082345678901" },
    ketuaPelaksana: { nama: "Anisa Rahmawati", nim: "2111016220034" },
    ketuaOrganisasi: { nama: "Bagas Nugroho", telp: "2011016210017" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 2" },
      { item: "Item 2", nama: "Sound System - 2" },
      { item: "Item 3", nama: "Podium - 1" },
      { item: "Item 4", nama: "Mikrofon Wireless - 4" },
      { item: "Item 5", nama: "Layar Proyektor - 2" },
    ],
    keterangan: "Seminar Nasional MIPA menghadirkan narasumber dari berbagai universitas dan lembaga penelitian nasional. Estimasi peserta mencapai 200 orang dari dalam dan luar universitas.",
  },
  {
    id: 12,
    noSurat: "-",
    kegiatan: "Pelatihan Kepemimpinan",
    tanggalPengajuan: "01-04-2025",
    tanggalPinjam: "05-04-2025",
    tanggalKembali: "05-04-2025",
    status: "Revisi",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "BEM FMIPA",
    penanggungJawab: { nama: "Dimas Prasetyo", telp: "082345678901" },
    ketuaPelaksana: { nama: "Rizal Hamdani", nim: "2211016210047" },
    ketuaOrganisasi: { nama: "Bagas Nugroho", telp: "2011016210017" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 1" },
      { item: "Item 2", nama: "Sound System - 1" },
    ],
    keterangan: "Surat perlu direvisi karena spesifikasi alat yang diminta tidak lengkap dan estimasi waktu penggunaan belum dicantumkan.",
  },
  {
    id: 13,
    noSurat: "I/SPH/016/HMM-FMIPA/2025",
    kegiatan: "Olimpiade Matematika",
    tanggalPengajuan: "20-03-2025",
    tanggalPinjam: "28-03-2025",
    tanggalKembali: "29-03-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "HMM FMIPA",
    penanggungJawab: { nama: "Taufik Hidayat", telp: "087890123456" },
    ketuaPelaksana: { nama: "Arifin Maulana", nim: "2211011210033" },
    ketuaOrganisasi: { nama: "Lilis Suryani", telp: "2111011210019" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 3" },
      { item: "Item 2", nama: "Layar Proyektor - 3" },
      { item: "Item 3", nama: "Sound System - 1" },
      { item: "Item 4", nama: "Stopwatch Digital - 5" },
    ],
    keterangan: "Olimpiade Matematika HMM FMIPA diikuti oleh perwakilan SMA/SMK se-Kalimantan Selatan. Kegiatan ini merupakan agenda tahunan untuk menjaring bibit matematikawan muda.",
  },
  {
    id: 14,
    noSurat: "-",
    kegiatan: "Workshop Kimia Dasar",
    tanggalPengajuan: "10-03-2025",
    tanggalPinjam: "15-03-2025",
    tanggalKembali: "15-03-2025",
    status: "Ditolak",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "HIMAKI FMIPA",
    penanggungJawab: { nama: "Nur Fadilah", telp: "083456000011" },
    ketuaPelaksana: { nama: "Andi Firmansyah", nim: "2311012210019" },
    ketuaOrganisasi: { nama: "Salma Aulia", telp: "2111012210007" },
    daftarAlat: [
      { item: "Item 1", nama: "Set Alat Laboratorium - 1" },
      { item: "Item 2", nama: "Proyektor - 1" },
    ],
    keterangan: "Ditolak karena set alat laboratorium yang diminta memerlukan izin khusus dari kepala laboratorium yang belum terlampir dalam surat.",
  },
  {
    id: 15,
    noSurat: "I/SPH/015/SGO-FMIPA/2025",
    kegiatan: "Pekan Geografi",
    tanggalPengajuan: "01-03-2025",
    tanggalPinjam: "08-03-2025",
    tanggalKembali: "10-03-2025",
    status: "Diterima",
    jenisSurat: "Surat Peminjaman Alat/Bahan",
    organisasi: "SGO",
    penanggungJawab: { nama: "Yusuf Maulana", telp: "086789012345" },
    ketuaPelaksana: { nama: "Dewi Kartika", nim: "2211013320016" },
    ketuaOrganisasi: { nama: "Hamdan Noor", telp: "2111013210005" },
    daftarAlat: [
      { item: "Item 1", nama: "Proyektor - 2" },
      { item: "Item 2", nama: "Sound System - 2" },
      { item: "Item 3", nama: "Peta Dinding - 5" },
      { item: "Item 4", nama: "Kompas - 10" },
    ],
    keterangan: "Pekan Geografi SGO adalah festival ilmiah tahunan yang menampilkan berbagai lomba dan pameran bertema geografi dan lingkungan hidup. Kegiatan ini terbuka untuk umum.",
  },
];

export const izinTidakMengikutiKuliahData = [
  {
    id: 1, noSurat: "225/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "10-06-2025",
    namaDosen: "Dr. Siti Rahayu, M.Pd.", prodiDosen: "Fisika", mataKuliah: "Bahasa Indonesia",
    tanggalMulai: "12-06-2025", tanggalAkhir: "12-06-2025",
    sebab: "Sakit dan harus beristirahat berdasarkan anjuran dokter",
    tempat: "Rumah, Banjarmasin", keterangan: "-",
    mahasiswas: [
      { nim: "2211014120003", nama: "Nasha Widya Andini", prodi: "S1 Fisika", mataKuliah: "Bahasa Indonesia" },
    ],
  },
  {
    id: 2, noSurat: "224/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "27-05-2025",
    namaDosen: "Triando Hamonangan Saragih", prodiDosen: "Ilmu Komputer", mataKuliah: "Matematika Diskrit",
    tanggalMulai: "28-05-2025", tanggalAkhir: "29-05-2025",
    sebab: "Mengikuti lomba pekan olahraga provinsi (PORPROV XII) cabor Drumband",
    tempat: "Pelaihari, Tanah Laut", keterangan: "-",
    mahasiswas: [
      { nim: "2211016120001", nama: "Najla Putri Kartika", prodi: "S1 Ilmu Komputer", mataKuliah: "Matematika Diskrit" },
      { nim: "2211016120009", nama: "Rizky Maulana Hakim", prodi: "S1 Ilmu Komputer", mataKuliah: "Matematika Diskrit" },
    ],
  },
  {
    id: 3, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "20-05-2025",
    namaDosen: "Dr. Hendra Kusuma, M.Kom.", prodiDosen: "Ilmu Komputer", mataKuliah: "Kecerdasan Buatan",
    tanggalMulai: "22-05-2025", tanggalAkhir: "22-05-2025",
    sebab: "Menghadiri pemakaman keluarga", tempat: "Martapura, Banjar",
    keterangan: "Surat perlu dilengkapi dengan bukti pendukung seperti surat keterangan kematian.",
    mahasiswas: [
      { nim: "2211016310018", nama: "Bhimo Noorasty Whibhisono", prodi: "S1 Ilmu Komputer", mataKuliah: "Kecerdasan Buatan" },
    ],
  },
  {
    id: 4, noSurat: "223/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "15-05-2025",
    namaDosen: "Dr. Rahmat Hidayat, M.T.", prodiDosen: "Ilmu Komputer", mataKuliah: "Analisis Numerik",
    tanggalMulai: "17-05-2025", tanggalAkhir: "18-05-2025",
    sebab: "Mewakili universitas dalam kompetisi pemrograman nasional ICPC",
    tempat: "Surabaya, Jawa Timur", keterangan: "-",
    mahasiswas: [
      { nim: "2311016210031", nama: "Ahmad Ryan Faizal", prodi: "S1 Ilmu Komputer", mataKuliah: "Analisis Numerik" },
      { nim: "2311016210044", nama: "Daffa Arya Nugraha", prodi: "S1 Ilmu Komputer", mataKuliah: "Analisis Numerik" },
      { nim: "2311016310055", nama: "Khairul Umam", prodi: "S1 Ilmu Komputer", mataKuliah: "Analisis Numerik" },
    ],
  },
  {
    id: 5, noSurat: "222/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "08-05-2025",
    namaDosen: "Nur Hasanah, M.Pd.", prodiDosen: "Farmasi", mataKuliah: "Bahasa Inggris 2",
    tanggalMulai: "10-05-2025", tanggalAkhir: "10-05-2025",
    sebab: "Kontrol rutin ke dokter spesialis karena kondisi kesehatan",
    tempat: "RS Ulin, Banjarmasin", keterangan: "-",
    mahasiswas: [
      { nim: "2110015320007", nama: "Helmina Salwa", prodi: "S1 Farmasi", mataKuliah: "Bahasa Inggris 2" },
    ],
  },
  {
    id: 6, noSurat: "221/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "08-05-2025",
    namaDosen: "Nur Hasanah, M.Pd.", prodiDosen: "Farmasi", mataKuliah: "Bahasa Inggris 1",
    tanggalMulai: "10-05-2025", tanggalAkhir: "10-05-2025",
    sebab: "Kontrol rutin ke dokter spesialis karena kondisi kesehatan",
    tempat: "RS Ulin, Banjarmasin", keterangan: "-",
    mahasiswas: [
      { nim: "2110015320007", nama: "Helmina Salwa", prodi: "S1 Farmasi", mataKuliah: "Bahasa Inggris 1" },
    ],
  },
  {
    id: 7, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "01-05-2025",
    namaDosen: "Dr. Bambang Susilo, M.H.", prodiDosen: "Farmasi", mataKuliah: "Kewarganegaraan",
    tanggalMulai: "05-05-2025", tanggalAkhir: "05-05-2025",
    sebab: "Keperluan keluarga mendadak", tempat: "Hulu Sungai Selatan",
    keterangan: "Ditolak karena tidak disertai bukti atau surat keterangan yang mendukung.",
    mahasiswas: [
      { nim: "2110015210036", nama: "Muhammad Ridho Maulana", prodi: "S1 Farmasi", mataKuliah: "Kewarganegaraan" },
    ],
  },
  {
    id: 8, noSurat: "220/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "18-04-2025",
    namaDosen: "apt. Diah Rahmawati, M.Farm.", prodiDosen: "Farmasi", mataKuliah: "Farmasetika",
    tanggalMulai: "20-04-2025", tanggalAkhir: "21-04-2025",
    sebab: "Mengikuti seminar nasional kefarmasian sebagai delegasi FMIPA",
    tempat: "Universitas Gadjah Mada, Yogyakarta", keterangan: "-",
    mahasiswas: [
      { nim: "2311015200012", nama: "Rismawati Meisya Siagian", prodi: "S1 Farmasi", mataKuliah: "Farmasetika" },
      { nim: "2311015320016", nama: "Putri Nabilah Fadilah", prodi: "S1 Farmasi", mataKuliah: "Farmasetika" },
    ],
  },
  {
    id: 9, noSurat: "219/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "10-04-2025",
    namaDosen: "Dr. Yuli Astuti, M.Si.", prodiDosen: "Kimia", mataKuliah: "Kimia Unsur",
    tanggalMulai: "12-04-2025", tanggalAkhir: "12-04-2025",
    sebab: "Sakit demam berdarah dan dirawat di rumah sakit",
    tempat: "RS Idaman, Banjarbaru", keterangan: "-",
    mahasiswas: [
      { nim: "2411012220005", nama: "Rifayah Oktaria Fitriani", prodi: "S1 Kimia", mataKuliah: "Kimia Unsur" },
    ],
  },
  {
    id: 10, noSurat: "218/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "05-04-2025",
    namaDosen: "Dr. Faisal Adnan, M.Si.", prodiDosen: "Matematika", mataKuliah: "Program Linear",
    tanggalMulai: "07-04-2025", tanggalAkhir: "07-04-2025",
    sebab: "Mengikuti olimpiade matematika tingkat nasional",
    tempat: "Institut Teknologi Bandung, Bandung", keterangan: "-",
    mahasiswas: [
      { nim: "2411000091131", nama: "Raihan Nooriman", prodi: "S1 Matematika", mataKuliah: "Program Linear" },
      { nim: "2311011210058", nama: "Hafizh Noor Ramadhan", prodi: "S1 Matematika", mataKuliah: "Program Linear" },
    ],
  },
  {
    id: 11, noSurat: "217/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "28-03-2025",
    namaDosen: "Dr. Wahyu Prihanta, M.Si.", prodiDosen: "Biologi", mataKuliah: "Ekologi Hewan",
    tanggalMulai: "30-03-2025", tanggalAkhir: "31-03-2025",
    sebab: "Mengikuti kegiatan KKN persiapan lapangan", tempat: "Pelaihari, Tanah Laut", keterangan: "-",
    mahasiswas: [
      { nim: "2311013110024", nama: "Siti Aisyah Ramadhani", prodi: "S1 Biologi", mataKuliah: "Ekologi Hewan" },
    ],
  },
  {
    id: 12, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "20-03-2025",
    namaDosen: "Irwan Budiman, M.T.", prodiDosen: "Ilmu Komputer", mataKuliah: "Pemrograman Web",
    tanggalMulai: "22-03-2025", tanggalAkhir: "22-03-2025",
    sebab: "Urusan keluarga di luar kota", tempat: "Balikpapan, Kalimantan Timur",
    keterangan: "Surat perlu dilampiri surat keterangan dari orang tua atau wali.",
    mahasiswas: [
      { nim: "2211016310045", nama: "Farhan Maulana Akbar", prodi: "S1 Ilmu Komputer", mataKuliah: "Pemrograman Web" },
    ],
  },
  {
    id: 13, noSurat: "216/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "12-03-2025",
    namaDosen: "apt. Rizky Mulyani, M.Farm.", prodiDosen: "Farmasi", mataKuliah: "Kimia Organik",
    tanggalMulai: "14-03-2025", tanggalAkhir: "14-03-2025",
    sebab: "Menghadiri wisuda kakak kandung di luar kota",
    tempat: "Universitas Lambung Mangkurat, Banjarmasin", keterangan: "-",
    mahasiswas: [
      { nim: "2411015320018", nama: "Nurul Hikmah Putri", prodi: "S1 Farmasi", mataKuliah: "Kimia Organik" },
    ],
  },
  {
    id: 14, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "05-03-2025",
    namaDosen: "Dr. Dodon Yendri, M.Kom.", prodiDosen: "Ilmu Komputer", mataKuliah: "Basis Data",
    tanggalMulai: "07-03-2025", tanggalAkhir: "07-03-2025",
    sebab: "Alasan pribadi", tempat: "-",
    keterangan: "Ditolak karena alasan tidak memenuhi kriteria izin resmi.",
    mahasiswas: [
      { nim: "2311016210009", nama: "Rizky Aditya Pratama", prodi: "S1 Ilmu Komputer", mataKuliah: "Basis Data" },
    ],
  },
  {
    id: 15, noSurat: "215/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "25-02-2025",
    namaDosen: "Prof. Dr. Suparno, M.Si.", prodiDosen: "Fisika", mataKuliah: "Fisika Kuantum",
    tanggalMulai: "27-02-2025", tanggalAkhir: "28-02-2025",
    sebab: "Mewakili FMIPA dalam ajang Science Fair tingkat nasional",
    tempat: "Jakarta Convention Center, Jakarta", keterangan: "-",
    mahasiswas: [
      { nim: "2211014120011", nama: "Aulia Rahma Sari", prodi: "S1 Fisika", mataKuliah: "Fisika Kuantum" },
      { nim: "2211014120019", nama: "Farida Nur Laila", prodi: "S1 Fisika", mataKuliah: "Fisika Kuantum" },
    ],
  },
  {
    id: 16, noSurat: "214/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "18-02-2025",
    namaDosen: "Dr. Husna Arifah, M.Sc.", prodiDosen: "Matematika", mataKuliah: "Kalkulus Lanjut",
    tanggalMulai: "20-02-2025", tanggalAkhir: "20-02-2025",
    sebab: "Sakit influenza dan demam tinggi", tempat: "Rumah, Banjarbaru", keterangan: "-",
    mahasiswas: [
      { nim: "2111011110033", nama: "Dimas Surya Wicaksono", prodi: "S1 Matematika", mataKuliah: "Kalkulus Lanjut" },
    ],
  },
  {
    id: 17, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "10-02-2025",
    namaDosen: "Dr. Eko Setyobudi, M.Si.", prodiDosen: "Biologi", mataKuliah: "Genetika",
    tanggalMulai: "12-02-2025", tanggalAkhir: "12-02-2025",
    sebab: "Pernikahan saudara kandung", tempat: "Amuntai, Hulu Sungai Utara",
    keterangan: "Surat perlu ditambahkan undangan pernikahan sebagai bukti pendukung.",
    mahasiswas: [
      { nim: "2311013110037", nama: "Indah Permata Dewi", prodi: "S1 Biologi", mataKuliah: "Genetika" },
    ],
  },
  {
    id: 18, noSurat: "213/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "05-02-2025",
    namaDosen: "Dr. Sri Wahyuni, M.Si.", prodiDosen: "Kimia", mataKuliah: "Kimia Analitik",
    tanggalMulai: "07-02-2025", tanggalAkhir: "08-02-2025",
    sebab: "Mengikuti lomba kimia analitik tingkat regional Kalimantan",
    tempat: "Universitas Mulawarman, Samarinda", keterangan: "-",
    mahasiswas: [
      { nim: "2411012220019", nama: "Bagas Tri Saputra", prodi: "S1 Kimia", mataKuliah: "Kimia Analitik" },
      { nim: "2411012220027", nama: "Annisa Hidayati", prodi: "S1 Kimia", mataKuliah: "Kimia Analitik" },
    ],
  },
  {
    id: 19, noSurat: "212/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "28-01-2025",
    namaDosen: "Muhammad Reza, M.Kom.", prodiDosen: "Ilmu Komputer", mataKuliah: "Jaringan Komputer",
    tanggalMulai: "30-01-2025", tanggalAkhir: "30-01-2025",
    sebab: "Mengikuti workshop jaringan komputer yang diselenggarakan Cisco Networking Academy",
    tempat: "Banjarbaru, Kalimantan Selatan", keterangan: "-",
    mahasiswas: [
      { nim: "2211016310052", nama: "Reza Maulana Firdaus", prodi: "S1 Ilmu Komputer", mataKuliah: "Jaringan Komputer" },
    ],
  },
  {
    id: 20, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "20-01-2025",
    namaDosen: "apt. Novita Sari, M.Farm.", prodiDosen: "Farmasi", mataKuliah: "Anatomi Fisiologi",
    tanggalMulai: "22-01-2025", tanggalAkhir: "22-01-2025",
    sebab: "Keperluan mendadak", tempat: "-",
    keterangan: "Ditolak karena surat tidak memenuhi syarat pengajuan minimal 2 hari sebelum tanggal izin.",
    mahasiswas: [
      { nim: "2310015320041", nama: "Cantika Dwi Rahayu", prodi: "S1 Farmasi", mataKuliah: "Anatomi Fisiologi" },
    ],
  },
  {
    id: 21, noSurat: "211/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "12-01-2025",
    namaDosen: "Dr. Noor Hidayat, M.Si.", prodiDosen: "Matematika", mataKuliah: "Statistika Dasar",
    tanggalMulai: "14-01-2025", tanggalAkhir: "14-01-2025",
    sebab: "Mengikuti pelatihan metodologi penelitian yang diselenggarakan FMIPA",
    tempat: "Gedung Rektorat ULM, Banjarmasin", keterangan: "-",
    mahasiswas: [
      { nim: "2111011110048", nama: "Wahyu Nugraha Santoso", prodi: "S1 Matematika", mataKuliah: "Statistika Dasar" },
    ],
  },
  {
    id: 22, noSurat: "210/UN8.1.28/KM/2025", status: "Diterima",
    jenisSurat: "Surat Izin Tidak Mengikuti Kuliah", tanggalPengajuan: "05-01-2025",
    namaDosen: "Dr. Hardiansyah, M.Si.", prodiDosen: "Biologi", mataKuliah: "Botani Umum",
    tanggalMulai: "07-01-2025", tanggalAkhir: "08-01-2025",
    sebab: "Mengikuti ekspedisi flora endemik Kalimantan bersama tim peneliti LIPI",
    tempat: "Pegunungan Meratus, Kalimantan Selatan", keterangan: "-",
    mahasiswas: [
      { nim: "2411013110006", nama: "Putri Nabilah Zahra", prodi: "S1 Biologi", mataKuliah: "Botani Umum" },
      { nim: "2411013110014", nama: "Gilang Putra Pratama", prodi: "S1 Biologi", mataKuliah: "Botani Umum" },
      { nim: "2311013220021", nama: "Nur Haafizah Az Zahra", prodi: "S1 Biologi", mataKuliah: "Botani Umum" },
    ],
  },
];

export const izinPraktikumUlangData = [
  {
    id: 1, noSurat: "155/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "15-06-2025",
    tanggalMulai: "18-06-2025", tanggalAkhir: "19-06-2025",
    sebab: "Sakit dan tidak dapat mengikuti praktikum pada jadwal yang telah ditentukan",
    tempat: "Laboratorium Farmasi FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2110015120012", nama: "Nor Aida", mataKuliah: "Farmasi Masyarakat", prodi: "S1 Farmasi" },
    ],
  },
  {
    id: 2, noSurat: "154/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "28-05-2025",
    tanggalMulai: "28-05-2025", tanggalAkhir: "29-05-2025",
    sebab: "Kegiatan Pemusatan Latihan Atlet Pencak Silat Kalsel 2025 dalam menghadapi Babak Kualifikasi PON",
    tempat: "GOR Stadion Mandiangin Barabai Kab. Hulu Sungai Tengah",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2011015220033", nama: "Dewiyana Purwaningrum", mataKuliah: "Farmasetika", prodi: "S1 Farmasi" },
      { nim: "2011015220041", nama: "Rizka Amalia Putri", mataKuliah: "Farmasetika", prodi: "S1 Farmasi" },
    ],
  },
  {
    id: 3, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "20-05-2025",
    tanggalMulai: "22-05-2025", tanggalAkhir: "22-05-2025",
    sebab: "Urusan keluarga mendadak di luar kota", tempat: "Laboratorium Kimia FMIPA ULM",
    keterangan: "Ditolak karena tidak disertai bukti yang memadai.",
    mahasiswas: [
      { nim: "2211012320006", nama: "Aida Fitriah", mataKuliah: "Kimia 1", prodi: "S1 Kimia" },
    ],
  },
  {
    id: 4, noSurat: "153/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "14-05-2025",
    tanggalMulai: "16-05-2025", tanggalAkhir: "16-05-2025",
    sebab: "Mengikuti kegiatan pengabdian masyarakat yang dijadwalkan bersamaan",
    tempat: "Laboratorium Biologi FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2211013310011", nama: "Muhammad Adi Hernanda", mataKuliah: "Saintekwan", prodi: "S1 Biologi" },
    ],
  },
  {
    id: 5, noSurat: "152/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "08-05-2025",
    tanggalMulai: "10-05-2025", tanggalAkhir: "10-05-2025",
    sebab: "Sakit dan mendapat surat istirahat dari dokter",
    tempat: "Laboratorium Jaringan Ilmu Komputer FMIPA ULM",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "1811016120006", nama: "Nurlatifah Amini", mataKuliah: "Jaringan Komputer", prodi: "S1 Ilmu Komputer" },
    ],
  },
  {
    id: 6, noSurat: "151/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "02-05-2025",
    tanggalMulai: "05-05-2025", tanggalAkhir: "05-05-2025",
    sebab: "Mengikuti lomba olimpiade biologi tingkat nasional",
    tempat: "Laboratorium Biologi FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    // dua peserta olimpiade biologi
    mahasiswas: [
      { nim: "2311013120009", nama: "Putri Dea Amelia", mataKuliah: "Biodiversitas", prodi: "S1 Biologi" },
      { nim: "2311013110024", nama: "Siti Aisyah Ramadhani", mataKuliah: "Biodiversitas", prodi: "S1 Biologi" },
    ],
  },
  {
    id: 7, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "25-04-2025",
    tanggalMulai: "27-04-2025", tanggalAkhir: "27-04-2025",
    sebab: "Keperluan mendadak", tempat: "Laboratorium Ilmu Komputer FMIPA ULM",
    keterangan: "Surat perlu dilengkapi dengan alasan yang lebih jelas dan bukti pendukung.",
    mahasiswas: [
      { nim: "2011016310054", nama: "Fajrin Azzimi", mataKuliah: "Pemrograman Lanjut", prodi: "S1 Ilmu Komputer" },
    ],
  },
  {
    id: 8, noSurat: "150/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "18-04-2025",
    tanggalMulai: "20-04-2025", tanggalAkhir: "21-04-2025",
    sebab: "Menghadiri seminar kefarmasian nasional sebagai delegasi himpunan",
    tempat: "Laboratorium Farmakologi FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2110015220021", nama: "Wananda Zahidahtun Nisa", mataKuliah: "Farmakokinetika", prodi: "S1 Farmasi" },
    ],
  },
  {
    id: 9, noSurat: "149/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "10-04-2025",
    tanggalMulai: "12-04-2025", tanggalAkhir: "12-04-2025",
    sebab: "Mengikuti hackathon tingkat regional Kalimantan",
    tempat: "Laboratorium Sistem Operasi Ilmu Komputer FMIPA ULM",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    // tiga anggota tim hackathon
    mahasiswas: [
      { nim: "2011016210023", nama: "Rifqi Fahmi Putra Kania", mataKuliah: "Sistem Operasi", prodi: "S1 Ilmu Komputer" },
      { nim: "2011016310054", nama: "Fajrin Azzimi", mataKuliah: "Sistem Operasi", prodi: "S1 Ilmu Komputer" },
      { nim: "2111016210038", nama: "Faris Maulana Ihsan", mataKuliah: "Sistem Operasi", prodi: "S1 Ilmu Komputer" },
    ],
  },
  {
    id: 10, noSurat: "148/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "03-04-2025",
    tanggalMulai: "05-04-2025", tanggalAkhir: "05-04-2025",
    sebab: "Sakit diare dan tidak dapat hadir sesuai jadwal praktikum",
    tempat: "Laboratorium Biokimia FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2311012220014", nama: "Dina Aprilia", mataKuliah: "Reaksi Biokimia", prodi: "S1 Kimia" },
    ],
  },
  {
    id: 11, noSurat: "147/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "25-03-2025",
    tanggalMulai: "27-03-2025", tanggalAkhir: "27-03-2025",
    sebab: "Mewakili universitas dalam kompetisi coding nasional",
    tempat: "Laboratorium Pemrograman Ilmu Komputer FMIPA ULM",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2111016210038", nama: "Faris Maulana Ihsan", mataKuliah: "Algoritma Pemrograman", prodi: "S1 Ilmu Komputer" },
    ],
  },
  {
    id: 12, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "18-03-2025",
    tanggalMulai: "20-03-2025", tanggalAkhir: "20-03-2025",
    sebab: "Keluarga sakit dan perlu pendampingan", tempat: "Laboratorium Biokimia FMIPA ULM",
    keterangan: "Surat perlu dilampiri surat keterangan sakit dari anggota keluarga.",
    mahasiswas: [
      { nim: "2311015320019", nama: "Muthia Rahmawati", mataKuliah: "Biokimia Farmasi", prodi: "S1 Farmasi" },
    ],
  },
  {
    id: 13, noSurat: "146/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "10-03-2025",
    tanggalMulai: "12-03-2025", tanggalAkhir: "13-03-2025",
    sebab: "Mengikuti pelatihan instrumentasi fisika tingkat nasional",
    tempat: "Laboratorium Fisika Modern FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2211014120027", nama: "Hendra Wijaya Kusuma", mataKuliah: "Fisika Modern", prodi: "S1 Fisika" },
    ],
  },
  {
    id: 14, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "01-03-2025",
    tanggalMulai: "03-03-2025", tanggalAkhir: "03-03-2025",
    sebab: "Alasan pribadi", tempat: "Laboratorium Mikrobiologi FMIPA ULM",
    keterangan: "Ditolak karena alasan tidak memenuhi kriteria izin resmi.",
    mahasiswas: [
      { nim: "2411013110044", nama: "Salsabila Nur Afifah", mataKuliah: "Mikrobiologi", prodi: "S1 Biologi" },
    ],
  },
  {
    id: 15, noSurat: "145/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "22-02-2025",
    tanggalMulai: "24-02-2025", tanggalAkhir: "24-02-2025",
    sebab: "Mengikuti lomba kimia analitik tingkat regional",
    tempat: "Laboratorium Kimia Fisika FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    // dua peserta lomba
    mahasiswas: [
      { nim: "2311012220031", nama: "Akbar Ramadhan Putra", mataKuliah: "Kimia Fisika", prodi: "S1 Kimia" },
      { nim: "2311012220014", nama: "Dina Aprilia", mataKuliah: "Kimia Fisika", prodi: "S1 Kimia" },
    ],
  },
  {
    id: 16, noSurat: "144/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "14-02-2025",
    tanggalMulai: "16-02-2025", tanggalAkhir: "16-02-2025",
    sebab: "Sakit dan mendapat surat istirahat dari dokter",
    tempat: "Laboratorium Matematika FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2111011110056", nama: "Tiara Kusuma Wardani", mataKuliah: "Analisis Real", prodi: "S1 Matematika" },
    ],
  },
  {
    id: 17, noSurat: "-", status: "Revisi",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "05-02-2025",
    tanggalMulai: "07-02-2025", tanggalAkhir: "07-02-2025",
    sebab: "Kegiatan organisasi berbenturan dengan jadwal praktikum",
    tempat: "Laboratorium Ilmu Komputer FMIPA ULM",
    keterangan: "Surat perlu dilampiri surat kegiatan resmi dari organisasi.",
    mahasiswas: [
      { nim: "2211016310063", nama: "Yoga Pratama Nugroho", mataKuliah: "Struktur Data", prodi: "S1 Ilmu Komputer" },
    ],
  },
  {
    id: 18, noSurat: "143/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "28-01-2025",
    tanggalMulai: "30-01-2025", tanggalAkhir: "30-01-2025",
    sebab: "Mengikuti seminar teknologi farmasi di luar kota",
    tempat: "Laboratorium Teknologi Sediaan FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2411015320008", nama: "Rizka Amalia Putri", mataKuliah: "Teknologi Sediaan", prodi: "S1 Farmasi" },
    ],
  },
  {
    id: 19, noSurat: "142/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "20-01-2025",
    tanggalMulai: "22-01-2025", tanggalAkhir: "22-01-2025",
    sebab: "Mengikuti ekspedisi flora Kalimantan bersama tim peneliti",
    tempat: "Laboratorium Ekologi FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2311013110022", nama: "Gilang Ramadhan Santoso", mataKuliah: "Ekologi Tumbuhan", prodi: "S1 Biologi" },
    ],
  },
  {
    id: 20, noSurat: "-", status: "Ditolak",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "10-01-2025",
    tanggalMulai: "12-01-2025", tanggalAkhir: "12-01-2025",
    sebab: "Keperluan mendadak", tempat: "Laboratorium Kimia Organik FMIPA ULM",
    keterangan: "Ditolak karena pengajuan melewati batas waktu yang ditentukan.",
    mahasiswas: [
      { nim: "2211012220049", nama: "Nadia Permatasari", mataKuliah: "Kimia Organik 2", prodi: "S1 Kimia" },
    ],
  },
  {
    id: 21, noSurat: "141/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "05-01-2025",
    tanggalMulai: "07-01-2025", tanggalAkhir: "08-01-2025",
    sebab: "Mengikuti olimpiade matematika tingkat nasional",
    tempat: "Laboratorium Matematika FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2111011110071", nama: "Arif Budiman Hakim", mataKuliah: "Persamaan Diferensial", prodi: "S1 Matematika" },
    ],
  },
  {
    id: 22, noSurat: "140/UN8.1.28/DT.01/2025", status: "Diterima",
    jenisSurat: "Surat Izin Praktikum Ulang", tanggalPengajuan: "02-01-2025",
    tanggalMulai: "04-01-2025", tanggalAkhir: "05-01-2025",
    sebab: "Sakit typhus dan dirawat di rumah sakit",
    tempat: "Laboratorium Fisika FMIPA ULM", keterangan: "Surat bisa diambil di bagian kemahasiswaan",
    mahasiswas: [
      { nim: "2411014120015", nama: "Dwi Rahayu Lestari", mataKuliah: "Termodinamika", prodi: "S1 Fisika" },
    ],
  },
];

export const rekomendasiData = [
  {
    id: 1,
    noSurat: "924/UN8.1.28/KM/2025",
    nama: "Naifah Azzahra",
    nim: "2411015220005",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "04-07-2025",
    status: "Diterima",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa Yayasan Pelita Bangsa tahun 2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 2,
    noSurat: "923/UN8.1.28/KM/2025",
    nama: "Zulfa Putri",
    nim: "2211015220021",
    prodi: "S1 Biologi",
    tanggalPengajuan: "02-07-2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "5",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan Program Bantuan Dana Pendidikan BAZNAS & PP Muhammadiyah 202",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 3,
    noSurat: "922/UN8.1.28/KM/2025",
    nama: "Listina Mahlidawati",
    nim: "2311013220004",
    prodi: "S1 Biologi",
    tanggalPengajuan: "26-06-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa prestasi akademik Pemda Kalimantan Selatan",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 4,
    noSurat: "921/UN8.1.28/KM/2025",
    nama: "Irfi Yusroini Pribadi",
    nim: "2311013320010",
    prodi: "S1 Biologi",
    tanggalPengajuan: "26-06-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan pengajuan beasiswa KIP Kuliah perpanjangan",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 5,
    noSurat: "-",
    nama: "Siti Nor Malisah",
    nim: "2311012320004",
    prodi: "S1 Kimia",
    tanggalPengajuan: "24-06-2025",
    status: "Ditolak",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan magang di perusahaan swasta",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Ditolak karena berkas persyaratan tidak lengkap.",
  },
  {
    id: 6,
    noSurat: "920/UN8.1.28/KM/2025",
    nama: "Raqib Abdul Haq",
    nim: "2311016110006",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "19-06-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan seleksi Program Magang Mahasiswa Berprestasi (PMMB) BUMN",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 7,
    noSurat: "919/UN8.1.28/KM/2025",
    nama: "Muhammad Nashir",
    nim: "2311011210023",
    prodi: "S1 Matematika",
    tanggalPengajuan: "28-04-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan mendaftar lomba matematika tingkat nasional",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 8,
    noSurat: "918/UN8.1.28/KM/2025",
    nama: "Abdul Rasyid Nasyar",
    nim: "2311011210012",
    prodi: "S1 Matematika",
    tanggalPengajuan: "28-04-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan mendaftar lomba matematika tingkat nasional",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 9,
    noSurat: "917/UN8.1.28/KM/2025",
    nama: "Aziza Humaira Rahmah",
    nim: "2311016220008",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "28-04-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan program pertukaran mahasiswa Merdeka Belajar",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 10,
    noSurat: "916/UN8.1.28/KM/2025",
    nama: "Vivia Windu Faustina",
    nim: "2211013220023",
    prodi: "S1 Biologi",
    tanggalPengajuan: "25-04-2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa riset dari Lembaga Pengelola Dana Pendidikan (LPDP)",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 11,
    noSurat: "915/UN8.1.28/KM/2025",
    nama: "Raihan Dwi Pratama",
    nim: "2311016210041",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "20-04-2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan internship di perusahaan teknologi nasional",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 12,
    noSurat: "-",
    nama: "Hana Salsabila Putri",
    nim: "2411015320016",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "15-04-2025",
    status: "Revisi",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa prestasi dari yayasan swasta",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu dilengkapi dengan transkrip nilai terbaru.",
  },
  {
    id: 13,
    noSurat: "914/UN8.1.28/KM/2025",
    nama: "Misbahul Munir",
    nim: "2211011110034",
    prodi: "S1 Matematika",
    tanggalPengajuan: "10-04-2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan pendaftaran olimpiade matematika internasional",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 14,
    noSurat: "-",
    nama: "Farida Nur Laila",
    nim: "2311012320029",
    prodi: "S1 Kimia",
    tanggalPengajuan: "05-04-2025",
    status: "Ditolak",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan program riset kolaborasi antar universitas",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Ditolak karena IPK tidak memenuhi syarat minimum yang ditentukan.",
  },
  {
    id: 15,
    noSurat: "913/UN8.1.28/KM/2025",
    nama: "Daffa Arya Wibowo",
    nim: "2211016210057",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "28-03-2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan seleksi Google Developer Student Club Lead",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 16,
    noSurat: "912/UN8.1.28/KM/2025",
    nama: "Syifa Aulia Rahma",
    nim: "2411013110009",
    prodi: "S1 Biologi",
    tanggalPengajuan: "20-03-2025",
    status: "Diterima",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa Bidikmisi perpanjangan semester genap",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 17,
    noSurat: "-",
    nama: "Ilham Maulana Yusuf",
    nim: "2311016310072",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "14-03-2025",
    status: "Revisi",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan program akselerasi startup kampus",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu dilengkapi proposal program yang jelas.",
  },
  {
    id: 18,
    noSurat: "911/UN8.1.28/KM/2025",
    nama: "Nabila Khairun Nisa",
    nim: "2111015220043",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "07-03-2025",
    status: "Diterima",
    angkatan: "2021",
    semester: "8",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan pendaftaran program apoteker di rumah sakit pemerintah",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 19,
    noSurat: "910/UN8.1.28/KM/2025",
    nama: "Rizki Aditya Firmansyah",
    nim: "2211014120018",
    prodi: "S1 Fisika",
    tanggalPengajuan: "28-02-2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan program riset bersama BRIN di bidang fisika terapan",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 20,
    noSurat: "-",
    nama: "Alifah Dwi Ramadhani",
    nim: "2311012220036",
    prodi: "S1 Kimia",
    tanggalPengajuan: "20-02-2025",
    status: "Ditolak",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan magang di laboratorium kimia industri",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Ditolak karena tidak memenuhi persyaratan administratif.",
  },
  {
    id: 21,
    noSurat: "909/UN8.1.28/KM/2025",
    nama: "Wahid Nur Hidayat",
    nim: "2111011110065",
    prodi: "S1 Matematika",
    tanggalPengajuan: "10-02-2025",
    status: "Diterima",
    angkatan: "2021",
    semester: "8",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa S2 dalam negeri Kemendikbud",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
  {
    id: 22,
    noSurat: "908/UN8.1.28/KM/2025",
    nama: "Putri Ayu Maharani",
    nim: "2411013110052",
    prodi: "S1 Biologi",
    tanggalPengajuan: "03-02-2025",
    status: "Diterima",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    keperluan: "Persyaratan beasiswa mahasiswa baru berprestasi tingkat FMIPA",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat bisa diambil di bagian kemahasiswaan",
  },
];

export const keteranganData = [
  {
    id: 1,
    noSurat: "872/UN8.1.28/KM/2025",
    nama: "Aaina Nabila Regena",
    nim: "2411013220006",
    prodi: "S1 Biologi",
    keperluan: "Beasiswa Unggul 2025",
    status: "Diterima",
    angkatan: "2024",
    semester: "3",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "10-07-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Unggul 2025",
  },
  {
    id: 2,
    noSurat: "871/UN8.1.28/KM/2025",
    nama: "Naifah Azzahra",
    nim: "2411015220005",
    prodi: "S1 Farmasi",
    keperluan: "Beasiswa Grab 2025",
    status: "Diterima",
    angkatan: "2024",
    semester: "3",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "02-07-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Grab 2025",
  },
  {
    id: 3,
    noSurat: "870/UN8.1.28/KM/2025",
    nama: "Putri Mulia Hasanah",
    nim: "2311012220003",
    prodi: "S1 Kimia",
    keperluan: "Djarum Beasiswa Plus 2025",
    status: "Revisi",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "28-06-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu dilengkapi dengan transkrip nilai terbaru dan foto terkini.",
  },
  {
    id: 4,
    noSurat: "-",
    nama: "Rifqi Pribadi Putra",
    nim: "2311013320032",
    prodi: "S1 Kimia",
    keperluan: "Pembuatan KTM baru",
    status: "Revisi",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "25-06-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu melampirkan bukti kehilangan KTM dari kepolisian.",
  },
  {
    id: 5,
    noSurat: "870/UN8.1.28/KM/2025",
    nama: "Lisa Ernawati",
    nim: "2211014220013",
    prodi: "S1 Biologi",
    keperluan: "Surat keterangan lomba LKTIB",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "20-06-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat keterangan keikutsertaan lomba LKTIB tingkat nasional",
  },
  {
    id: 6,
    noSurat: "869/UN8.1.28/KM/2025",
    nama: "Safianus Dulo",
    nim: "2111014210004",
    prodi: "S1 Fisika",
    keperluan: "Beasiswa Pertamina 2025",
    status: "Diterima",
    angkatan: "2021",
    semester: "8",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "15-06-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Pertamina 2025",
  },
  {
    id: 7,
    noSurat: "868/UN8.1.28/KM/2025",
    nama: "Raqib Abdul Haq",
    nim: "2311016110006",
    prodi: "S1 Ilmu Komputer",
    keperluan: "Beasiswa Kaltara Unggul 2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "10-06-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Kaltara Unggul 2025",
  },
  {
    id: 8,
    noSurat: "-",
    nama: "Helen Angelina Siburian",
    nim: "2211013310012",
    prodi: "S1 Statistika",
    keperluan: "Beasiswa Pendidikan Baznas",
    status: "Ditolak",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "05-06-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Ditolak karena IPK tidak memenuhi syarat minimum beasiswa.",
  },
  {
    id: 9,
    noSurat: "867/UN8.1.28/KM/2025",
    nama: "Uswetun Hasanah",
    nim: "2211014220056",
    prodi: "S1 Fisika",
    keperluan: "Pemutakhiran BPJS",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "28-05-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan pemutakhiran data BPJS",
  },
  {
    id: 10,
    noSurat: "866/UN8.1.28/KM/2025",
    nama: "Annisa Hidayati",
    nim: "2311012320013",
    prodi: "S1 Kimia",
    keperluan: "Djarum Beasiswa Plus 2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "20-05-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Djarum Beasiswa Plus 2025",
  },
  {
    id: 11,
    noSurat: "865/UN8.1.28/KM/2025",
    nama: "Muhamad Ilham Noor",
    nim: "2211016210047",
    prodi: "S1 Ilmu Komputer",
    keperluan: "Beasiswa Bank Indonesia 2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "12-05-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Bank Indonesia 2025",
  },
  {
    id: 12,
    noSurat: "-",
    nama: "Dewi Ayu Lestari",
    nim: "2411015320024",
    prodi: "S1 Farmasi",
    keperluan: "Surat keterangan aktif kuliah",
    status: "Revisi",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "05-05-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu dilengkapi dengan KRS semester berjalan.",
  },
  {
    id: 13,
    noSurat: "864/UN8.1.28/KM/2025",
    nama: "Bayu Setiawan Nugraha",
    nim: "2311011210039",
    prodi: "S1 Matematika",
    keperluan: "Beasiswa Yayasan Sampoerna",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "25-04-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Yayasan Sampoerna",
  },
  {
    id: 14,
    noSurat: "863/UN8.1.28/KM/2025",
    nama: "Ratna Sari Dewi",
    nim: "2211013120018",
    prodi: "S1 Biologi",
    keperluan: "Surat keterangan lomba PIMNAS",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "15-04-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Surat keterangan keikutsertaan PIMNAS tingkat nasional",
  },
  {
    id: 15,
    noSurat: "-",
    nama: "Fahmi Akbar Ramadhan",
    nim: "2311016310081",
    prodi: "S1 Ilmu Komputer",
    keperluan: "Pembuatan rekening bank",
    status: "Ditolak",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "05-04-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Ditolak karena keperluan tidak termasuk dalam kategori surat keterangan yang dapat diproses.",
  },
  {
    id: 16,
    noSurat: "862/UN8.1.28/KM/2025",
    nama: "Nur Aisyah Ramadhani",
    nim: "2111015220061",
    prodi: "S1 Farmasi",
    keperluan: "Beasiswa Grab 2025",
    status: "Diterima",
    angkatan: "2021",
    semester: "8",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "25-03-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Grab 2025",
  },
  {
    id: 17,
    noSurat: "861/UN8.1.28/KM/2025",
    nama: "Wahyu Hidayatullah",
    nim: "2211014120029",
    prodi: "S1 Fisika",
    keperluan: "Beasiswa Unggul 2025",
    status: "Diterima",
    angkatan: "2022",
    semester: "6",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "15-03-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Unggul 2025",
  },
  {
    id: 18,
    noSurat: "-",
    nama: "Siti Khadijah Amini",
    nim: "2411012320007",
    prodi: "S1 Kimia",
    keperluan: "Surat keterangan aktif kuliah",
    status: "Revisi",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "05-03-2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    keterangan: "Surat perlu dilengkapi dengan KRS dan bukti pembayaran UKT.",
  },
  {
    id: 19,
    noSurat: "860/UN8.1.28/KM/2025",
    nama: "Rizky Maulana Hakim",
    nim: "2311016210053",
    prodi: "S1 Ilmu Komputer",
    keperluan: "Beasiswa Kaltara Unggul 2025",
    status: "Diterima",
    angkatan: "2023",
    semester: "4",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "20-02-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Kaltara Unggul 2025",
  },
  {
    id: 20,
    noSurat: "859/UN8.1.28/KM/2025",
    nama: "Putri Nabilah Zahra",
    nim: "2411013110006",
    prodi: "S1 Biologi",
    keperluan: "Beasiswa Pendidikan Baznas",
    status: "Diterima",
    angkatan: "2024",
    semester: "2",
    tahunAjaran: "2024/2025",
    tanggalPengajuan: "10-02-2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    keterangan: "Untuk kebutuhan dalam mengajukan Beasiswa Pendidikan Baznas",
  },
];

export const keteranganMahasiswaKuliahData = [
  {
    id: 1,
    noSurat: "115/UN8.1.28/KM/2025",
    nama: "Ria Ali Yuniar",
    nim: "2211015320009",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "09-07-2025",
    status: "Diterima",
    semester: "2",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "01-01-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Salman",
    nipOrtu: "81100454",
    instansiOrtu: "POLRI",
    pangkatOrtu: "AIPTU",
    jabatanOrtu: "PS Panit Intelkam Polsek Kelumpang Hilir Polres Ko",
    keterangan: "Pengajuan untuk surat mahasiswa aktif keperluan Perpanjangan BPJS",
  },
  {
    id: 2,
    noSurat: "114/UN8.1.28/KM/2025",
    nama: "Risala Akfa Ridan",
    nim: "2211016210008",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "09-07-2025",
    status: "Ditolak",
    semester: "6",
    tempatLahir: "Banjarbaru",
    tanggalLahir: "15-03-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Ahmad Ridan",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Wirausaha",
    keterangan: "Ditolak karena data mahasiswa tidak sesuai dengan sistem akademik.",
  },
  {
    id: 3,
    noSurat: "114/UN8.1.28/KM/2025",
    nama: "Nur Haafizah Az Zahra",
    nim: "2311013220021",
    prodi: "S1 Biologi",
    tanggalPengajuan: "08-07-2025",
    status: "Diterima",
    semester: "4",
    tempatLahir: "Martapura",
    tanggalLahir: "22-06-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Hafidzurahman",
    nipOrtu: "19720505 199803 1 005",
    instansiOrtu: "Kementerian Agama",
    pangkatOrtu: "Penata/IIIc",
    jabatanOrtu: "Penyuluh Agama Islam Fungsional",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan beasiswa",
  },
  {
    id: 4,
    noSurat: "113/UN8.1.28/KM/2025",
    nama: "Naifah Azzahra",
    nim: "2411015220005",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "08-07-2025",
    status: "Diterima",
    semester: "2",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "10-11-2005",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Arif Azhari",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Pegawai Swasta",
    keterangan: "Surat keterangan aktif kuliah keperluan perpanjangan KIP Kuliah",
  },
  {
    id: 5,
    noSurat: "112/UN8.1.28/KM/2025",
    nama: "Putri Raudlatul Jannah",
    nim: "2211014220003",
    prodi: "S1 Fisika",
    tanggalPengajuan: "16-07-2025",
    status: "Diterima",
    semester: "6",
    tempatLahir: "Amuntai",
    tanggalLahir: "30-04-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Raudlah",
    nipOrtu: "19680212 199403 1 008",
    instansiOrtu: "Dinas Pendidikan",
    pangkatOrtu: "Pembina/IVa",
    jabatanOrtu: "Kepala Sekolah SMP Negeri 1 Amuntai",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan administrasi beasiswa",
  },
  {
    id: 6,
    noSurat: "-",
    nama: "Shauqi Aulia Rifwenda",
    nim: "2311012320018",
    prodi: "S1 Kimia",
    tanggalPengajuan: "22-07-2025",
    status: "Revisi",
    semester: "4",
    tempatLahir: "Kandangan",
    tanggalLahir: "07-08-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Rifwendi",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Wiraswasta",
    keterangan: "Surat perlu melampirkan KRS semester berjalan yang sudah disetujui.",
  },
  {
    id: 7,
    noSurat: "111/UN8.1.28/KM/2025",
    nama: "Muhammad Ali Rizqon",
    nim: "2211011110010",
    prodi: "S1 Matematika",
    tanggalPengajuan: "03-06-2025",
    status: "Diterima",
    semester: "6",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "12-05-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Rizqon Fathurrohman",
    nipOrtu: "19670918 199203 1 004",
    instansiOrtu: "Universitas Lambung Mangkurat",
    pangkatOrtu: "Lektor Kepala/IVb",
    jabatanOrtu: "Dosen Fakultas Keguruan",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan LPDP",
  },
  {
    id: 8,
    noSurat: "110/UN8.1.28/KM/2025",
    nama: "Awi Nartaliwa",
    nim: "2011016320017",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "15-06-2025",
    status: "Diterima",
    semester: "10",
    tempatLahir: "Palangka Raya",
    tanggalLahir: "25-09-2001",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Nartaliwa",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Pegawai Swasta",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan perpanjangan cicilan bank",
  },
  {
    id: 9,
    noSurat: "-",
    nama: "Muhammad Kamali Khotami",
    nim: "2211016210028",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "24-06-2025",
    status: "Ditolak",
    semester: "6",
    tempatLahir: "Barabai",
    tanggalLahir: "03-02-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Khotami",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Pedagang",
    keterangan: "Ditolak karena status mahasiswa sedang cuti akademik.",
  },
  {
    id: 10,
    noSurat: "109/UN8.1.28/KM/2025",
    nama: "Muhammad Akmal Perdana",
    nim: "2211017110007",
    prodi: "S1 Statistika",
    tanggalPengajuan: "28-05-2025",
    status: "Diterima",
    semester: "6",
    tempatLahir: "Banjarbaru",
    tanggalLahir: "18-07-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Perdana Kusuma",
    nipOrtu: "19720310 199903 1 007",
    instansiOrtu: "BPS Kalimantan Selatan",
    pangkatOrtu: "Penata Tingkat I/IIId",
    jabatanOrtu: "Kepala Seksi Statistik Distribusi",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan magang BPS",
  },
  {
    id: 11,
    noSurat: "108/UN8.1.28/KM/2025",
    nama: "Salsabila Putri Utami",
    nim: "2311015320041",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "20-05-2025",
    status: "Diterima",
    semester: "4",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "29-11-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Utami Dewi",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Ibu Rumah Tangga",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan beasiswa Baznas",
  },
  {
    id: 12,
    noSurat: "-",
    nama: "Dimas Arya Pradana",
    nim: "2211016310066",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "14-05-2025",
    status: "Revisi",
    semester: "6",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "14-04-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Arya Kusuma",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Pegawai Swasta",
    keterangan: "Surat perlu dilengkapi dengan data orang tua yang valid.",
  },
  {
    id: 13,
    noSurat: "107/UN8.1.28/KM/2025",
    nama: "Aulia Fitri Rahmawati",
    nim: "2411013110033",
    prodi: "S1 Biologi",
    tanggalPengajuan: "07-05-2025",
    status: "Diterima",
    semester: "2",
    tempatLahir: "Pelaihari",
    tanggalLahir: "17-08-2005",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Rahmawati",
    nipOrtu: "19751122 200012 2 003",
    instansiOrtu: "Puskesmas Pelaihari",
    pangkatOrtu: "Penata/IIIc",
    jabatanOrtu: "Bidan Puskesmas",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan KIP Kuliah",
  },
  {
    id: 14,
    noSurat: "106/UN8.1.28/KM/2025",
    nama: "Rizka Amalia Fauzi",
    nim: "2111014120044",
    prodi: "S1 Fisika",
    tanggalPengajuan: "28-04-2025",
    status: "Diterima",
    semester: "8",
    tempatLahir: "Rantau",
    tanggalLahir: "05-06-2002",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Fauzi Rahman",
    nipOrtu: "19700405 199503 1 011",
    instansiOrtu: "Dinas PUPR Kab. Tapin",
    pangkatOrtu: "Pembina/IVa",
    jabatanOrtu: "Kepala Bidang Sumber Daya Air",
    keterangan: "Surat keterangan aktif kuliah untuk administrasi bank",
  },
  {
    id: 15,
    noSurat: "-",
    nama: "Hafizh Noor Ramadhan",
    nim: "2311011210059",
    prodi: "S1 Matematika",
    tanggalPengajuan: "20-04-2025",
    status: "Ditolak",
    semester: "4",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "20-02-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Noor Ramadhan",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Wiraswasta",
    keterangan: "Ditolak karena mahasiswa tidak memenuhi syarat kehadiran minimum.",
  },
  {
    id: 16,
    noSurat: "105/UN8.1.28/KM/2025",
    nama: "Intan Permata Sari",
    nim: "2211012220037",
    prodi: "S1 Kimia",
    tanggalPengajuan: "12-04-2025",
    status: "Diterima",
    semester: "6",
    tempatLahir: "Banjarbaru",
    tanggalLahir: "09-09-2003",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Permata Hadi",
    nipOrtu: "19680901 199203 1 009",
    instansiOrtu: "BPKD Kab. Banjarbaru",
    pangkatOrtu: "Pembina Utama Muda/IVc",
    jabatanOrtu: "Kepala Badan Pengelolaan Keuangan Daerah",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan beasiswa daerah",
  },
  {
    id: 17,
    noSurat: "104/UN8.1.28/KM/2025",
    nama: "Fadli Akbar Maulana",
    nim: "2311016210072",
    prodi: "S1 Ilmu Komputer",
    tanggalPengajuan: "05-04-2025",
    status: "Diterima",
    semester: "4",
    tempatLahir: "Kandangan",
    tanggalLahir: "27-11-2004",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Akbar Wahid",
    nipOrtu: "-",
    instansiOrtu: "TNI AD",
    pangkatOrtu: "Serda",
    jabatanOrtu: "Anggota Satuan Yonif 621 Manuntung",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan tunjangan anak TNI",
  },
  {
    id: 18,
    noSurat: "-",
    nama: "Novia Rahmah Wulandari",
    nim: "2411015220019",
    prodi: "S1 Farmasi",
    tanggalPengajuan: "28-03-2025",
    status: "Revisi",
    semester: "2",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "03-07-2005",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "-",
    jabatan: "-",
    nip: "-",
    pangkat: "-",
    namaOrtu: "Wulandari",
    nipOrtu: "-",
    instansiOrtu: "Swasta",
    pangkatOrtu: "-",
    jabatanOrtu: "Ibu Rumah Tangga",
    keterangan: "Surat perlu dilengkapi dengan kartu keluarga terbaru.",
  },
  {
    id: 19,
    noSurat: "103/UN8.1.28/KM/2025",
    nama: "Gilang Putra Pratama",
    nim: "2211013110048",
    prodi: "S1 Biologi",
    tanggalPengajuan: "20-03-2025",
    status: "Diterima",
    semester: "6",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "14-12-2002",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Pratama Jaya",
    nipOrtu: "19721214 200012 1 005",
    instansiOrtu: "BPOM Kalimantan Selatan",
    pangkatOrtu: "Penata Tingkat I/IIId",
    jabatanOrtu: "Kepala Seksi Pengawasan Obat",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan administrasi beasiswa riset",
  },
  {
    id: 20,
    noSurat: "102/UN8.1.28/KM/2025",
    nama: "Syahrul Ramadhan Hakim",
    nim: "2111011110083",
    prodi: "S1 Matematika",
    tanggalPengajuan: "10-03-2025",
    status: "Diterima",
    semester: "8",
    tempatLahir: "Tanjung",
    tanggalLahir: "11-10-2001",
    tahunAjaran: "2024/2025",
    disetujuiOleh: "Mohammad Reza Faisal, S.T., MT., Ph.D",
    jabatan: "Wakil Dekan Bidang Kemahasiswaan dan Alumni",
    nip: "197612202008121001",
    pangkat: "Penata Tingkat I/IIId",
    namaOrtu: "Hakim Nugraha",
    nipOrtu: "19680308 199603 1 003",
    instansiOrtu: "Pengadilan Negeri Tanjung",
    pangkatOrtu: "Pembina/IVa",
    jabatanOrtu: "Hakim Pengadilan Negeri",
    keterangan: "Surat keterangan aktif kuliah untuk keperluan pendaftaran CPNS",
  },
];